version: "3"
services:
    db:
        image: postgres:latest
        restart: always
        environment:
            POSTGRES_USER: gabriel
            POSTGRES_PASSWORD: password
            POSTGRES_DB: venx
        ports:
            - 5432:5432
        volumes:
            - ./pgdata:/var/lib/postgresql/data
